name: Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main  # Or the name of your main branch

env:
  AZURE_WEBAPP_NAME: 'bkhadka'  # set this to your application's name
  NODE_VERSION: '20.x'  # Set the Node.js version to use

jobs:

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
